### ISSUE TITLE
[Bug]: In NavigationMenu with a NavigationMenuSub, pressing `tab` skips the item it should focus on next

### ISSUE THREAD

**Issue by olivoil** [radix-vue/radix-vue#1191]
### Environment

```bash
radix-vue: "1.9.3"
vue: "3.4.36"
Client OS: macOS 14.5 Sonoma
Browser: Arc Version 1.54.0 (52220)
Chromium Engine: Version 127.0.6533.89
```

### Link to minimal reproduction

https://stackblitz.com/edit/nq6vgu?file=src%2FApp.vue

### Steps to reproduce

in the stackblitz link provided with the reproduction,
open the first menu item called "Learn"
press "tab" twice so that the item called "Introduction Sub Item 1a" has focus

![image](https://github.com/user-attachments/assets/4c2d5d02-f600-42c1-9d09-a32836f09233)

press "tab" once more to focus on the next item in the "sub menu 1" list

### Describe the bug

The focus will skip the second item, and will jump to the 3rd item:

![image](https://github.com/user-attachments/assets/9d0cee5c-643b-4cd2-a72e-38cf94e3e41e)

### Expected behavior

Focus should go to the next sub item when pressing tab, and should not skip any items

![image](https://github.com/user-attachments/assets/4da00f09-b748-443c-acaf-1bf05a4e39e5)

### Context & Screenshots (if applicable)

Pressing `tab` in a sub menu seems to skip the next item consistently.
This seems like a bug, maybe the keypress action for `tab` runs twice when in a submenu? 

Although I am not sure if it could be because I am using the NavigationMenuSub incorrectly.

**Comment by ploca14** [comment]
After updating the repro to 1.9.5 the tab forward works correctly. But tabbing backwards with Shift+Tab is not working in the correct order.

Updated repro: https://stackblitz.com/edit/nq6vgu-4abrci?file=src%2FApp.vue

open the first menu item called "Learn"
press "tab" so that the item called "Sub menu 1" has focus

![image](https://github.com/user-attachments/assets/ebaa4f44-ecff-4f52-bac5-4c7a00b83a9c)

press "shift" + "tab" to focus back on the "Learn" item

The focus will jump to the "Overview" item.

![image](https://github.com/user-attachments/assets/27af4e72-2fca-4dec-b126-f4c90369d2ef)

Focus should go back to the "Learn" item

![image](https://github.com/user-attachments/assets/c707533c-293a-41c3-9391-9a1ef097e7e4)
