### ISSUE TITLE
[Vue warn]: injection "Symbol()" not found.

### ISSUE THREAD

**Issue by Gerbuuun** [radix-vue/radix-vue#229]
**Describe the bug**
```html
<template>
  <DropdownMenuRoot>
    <DropdownMenuTrigger>
      <Icon name="radix-icons:hamburger-menu" />
    </DropdownMenuTrigger>

    <DropdownMenuPortal>
      <DropdownMenuContent>
        <DropdownMenuItem>Test</DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenuPortal>
  </DropdownMenuRoot>
</template>

<script setup lang="ts">
import {
  DropdownMenuRoot,
  DropdownMenuTrigger,
  DropdownMenuPortal,
  DropdownMenuContent,
  DropdownMenuItem,
} from "radix-vue";
</script>
```
When I use this component in my Nuxt v3.6.5 project, I get the following warning
```bash
[Vue warn]: injection "Symbol()" not found.
```
Github copilot gave the following explanation:
```
This warning is usually caused by a mismatch between the version of Vue used by your application and the version of a Vue library or plugin that you are using. The Symbol() injection is used by Vue to provide a unique identifier for each component instance, and if it is not found, it can cause errors or unexpected behavior.

To resolve this issue, you can try the following steps:

1. Make sure that you are using compatible versions of Vue and any Vue libraries or plugins that you are using. Check the documentation for each library or plugin to see which versions of Vue they are compatible with.

2. If you are using Vue 3, make sure that any Vue libraries or plugins that you are using are also compatible with Vue 3. Some libraries and plugins may not yet be updated to work with Vue 3.

3. If you are using a build tool like Webpack or Rollup, make sure that you are correctly configuring the build to include all necessary dependencies.

4. If you are using a library or plugin that provides its own version of Vue, make sure that you are not including multiple versions of Vue in your application. This can cause conflicts and errors.
```

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4.1c
 - Browser: Brave
 - Version 1.52.130 Chromium: 114.0.5735.198

**Comment by smastrom** [comment]
@khairulhaaziq @uyloal Hi guys, I can submit a PR that fixes those SSR warnings anywhere needed as I have already dealt with this issue.

The reason why this is happening is that on the server, `inject` (imported from `vue`) simply doesn't work as it would in a vanilla Vue setup. Nuxt executes the setup function twice: once on the server and once on the client.

On the server it warns you as expected and on the client everything works as expected as well.

Nuxt can actually provide/inject only in the Vue App, but in order to do that, it needs first to gain access to the NuxtApp and then the Vue App. (`useNuxtApp().vueApp.provide()`). 

However, since this is not a Nuxt-specific package, the solution mentioned above is not suitable for Radix Vue as it would break functionalities on vanilla Vue setups. What instead could be done is to create provide/inject functions that simply will provide/inject mock values on the server and do what they're supposed to do once the Vue App kicks in.

Let me know if that's fine for you and I can submit a PR that fixes the warnings everywhere needed.

**Comment by smastrom** [comment]
@khairulhaaziq @uyloal Hi guys, I can submit a PR that fixes those SSR warnings anywhere needed as I have already dealt with this issue.

The reason why this is happening is that on the server, `provide` and `inject` (imported from `vue`) simply don't work. Those functions need to access the Vue App instance, which is not ready until, on the client, Nuxt hydrates the page. 

Nuxt executes the setup function twice: once on the server and once on the client.

On the server it warns you as expected and on then on the client everything works as expected as well. That's the reason why everything works on Nuxt.

Nuxt can actually provide/inject only in the Vue App, but in order to do that, it needs first to gain access to the NuxtApp and then the Vue App. (`useNuxtApp().vueApp.provide()`). 

However, since this is not a Nuxt-specific package, the solution mentioned above is not suitable for Radix Vue as it won't work on vanilla Vue setups. What instead can be done is to create provide/inject utils that simply will provide/inject mock values on the server and then do what they're supposed to do once called on the client.

Let me know if that's fine for you and I can submit a PR that fixes the warnings everywhere needed.

**Comment by BayBreezy** [comment]
Replying here to see if the proposed solution gets implemented lol. Thanks @smastrom

**Comment by khairulhaaziq** [comment]
> @khairulhaaziq @uyloal Hi guys, I can submit a PR that fixes those SSR warnings anywhere needed as I have already dealt with this issue.
> 
> The reason why this is happening is that on the server, `provide` and `inject` (imported from `vue`) simply don't work. Those functions need to access the Vue App instance, which is not ready until, on the client, Nuxt hydrates the page.
> 
> Nuxt executes the setup function twice: once on the server and once on the client.
> 
> On the server it warns you as expected and on then on the client everything works as expected as well. That's the reason why everything works on Nuxt.
> 
> Nuxt can actually provide/inject only in the Vue App, but in order to do that, it needs first to gain access to the NuxtApp and then the Vue App. (`useNuxtApp().vueApp.provide()`).
> 
> However, since this is not a Nuxt-specific package, the solution mentioned above is not suitable for Radix Vue as it won't work on vanilla Vue setups. What instead can be done is to create provide/inject utils that simply will provide/inject mock values on the server and then do what they're supposed to do once called on the client.
> 
> Let me know if that's fine for you and I can submit a PR that fixes the warnings everywhere needed.

@zernonia

**Comment by zernonia** [comment]
Hey @smastrom I do think provide/inject is working for SSR. I've commented [here](https://github.com/radix-vue/radix-vue/pull/246#issuecomment-1649820089) related to the findings.

**Comment by smastrom** [comment]
You're right, provide/inject has also issues on the frontend.

That doesn't take away the fact that on the server the warning (which is not an error and you're right that components work with Nuxt once on the client) is returned:

![Screenshot 2023-07-30 alle 12 35 27](https://github.com/radix-vue/radix-vue/assets/60471784/511224ee-f2aa-4fa8-927e-105bcd33ffc0)

This screenshot is from my terminal (which logs SSR), and this can be fixed as explained in the previous message (mocking inject when rendering on the server).

<br />

That said, I checked the injection warnings on the frontend. Basically, the reasons are:

1. In some places, inject is called before provide. So there's nothing to inject.

https://github.com/radix-vue/radix-vue/blob/7feb0c6df0b60a4a85e36fd50f16c6113e0227f7/packages/radix-vue/src/DropdownMenu/DropdownMenuSub.vue#L52-L54

https://github.com/radix-vue/radix-vue/blob/7feb0c6df0b60a4a85e36fd50f16c6113e0227f7/packages/radix-vue/src/shared/useCollection.ts#L13-L19

2. Sometimes inject is called assuming that a value is provided, but it's not, for example DropdownMenuItem can or cannot be child of a sub-menu (if it's not, the injection fails).

https://github.com/radix-vue/radix-vue/blob/7feb0c6df0b60a4a85e36fd50f16c6113e0227f7/packages/radix-vue/src/DropdownMenu/DropdownMenuItem.vue#L25-L27

Now, I have some ideas on how to fix everything, but this will require some effort because some of the provide/inject logic should be refactored (as well as composables like useCollection). Let me know if it's ok for you and I can provide some code.

**Comment by smastrom** [comment]
Hi @zernonia, that doesn't take away the fact that on the server the warning (which is not an error) is returned:

![Screenshot 2023-07-30 alle 12 35 27](https://github.com/radix-vue/radix-vue/assets/60471784/511224ee-f2aa-4fa8-927e-105bcd33ffc0)

This screenshot is from my terminal (which logs SSR), and this can be fixed as explained in the previous message (mocking inject when rendering on the server).

<br />

Then, as mentioned in the PR you linked, provide/inject also have issues on the frontend, but not because it's mounting recursively, the situation is a bit more complicated and affects multiple components of radix-vue.

I checked the injection warnings on the frontend. Basically, some of the reasons I found are:

1. In some places, inject is called before provide. So there's nothing to inject.

https://github.com/radix-vue/radix-vue/blob/7feb0c6df0b60a4a85e36fd50f16c6113e0227f7/packages/radix-vue/src/DropdownMenu/DropdownMenuSub.vue#L52-L54

https://github.com/radix-vue/radix-vue/blob/7feb0c6df0b60a4a85e36fd50f16c6113e0227f7/packages/radix-vue/src/shared/useCollection.ts#L13-L19

2. Sometimes inject is called assuming that a value is provided, but it's not, for example DropdownMenuItem can or cannot be child of a sub-menu (if it's not, the injection fails).

https://github.com/radix-vue/radix-vue/blob/7feb0c6df0b60a4a85e36fd50f16c6113e0227f7/packages/radix-vue/src/DropdownMenu/DropdownMenuItem.vue#L25-L27

<br />

I have some ideas on how to fix everything, but this will require some effort because some of the provide/inject logic should be refactored (as well as composables like useCollection which could not use provide/inject at all). Let me know if it's ok for you, and I'll be happy to help.

**Comment by zernonia** [comment]
Hey @smastrom , perhaps my explanation in the PR wasn't entirely clear.

It's ok to have the `WARNING`, it doesn't break anything. And yes, I am aware that some cases injected value is `undefined` due to it is not being provided before injecting, which happens with `useCollection` composables (as you mentioned), and some recursive component (mainly SUB component).
 
Thank you for your thorough explanation, but I wanna clarify something:
1. There's nothing wrong with `provide/inject` using SSR. (the warning is the same on server as in client).
2. The warning is just to warn the dev that `injected` value is undefined cause there's no context `provided`.


However, I would still love to hear your proposal for improving this! Perhaps create a simple PR just to demonstrate before executing all the changes? 😁

**Comment by smastrom** [comment]
> It's ok to have the `WARNING`, it doesn't break anything.

Although I do disagree with this sentence because in my opinion injecting the same key before providing it (in the same file) will definitely break things at some point, this is what currently happens for 1 dropdown once on the client.

https://github.com/radix-vue/radix-vue/assets/60471784/12cec7a9-9a43-409a-b101-354b604dd5aa

Six warnings are returned from a single trigger and navigation.

Imagine what could happen if the dropdown is used 10 times and on the page there are 4 dropdowns. 6 * 10 * 4 = 240 warnings. And this is only for the dropdown, not counting the other components exported by this package which are affected by the same behavior. In a complex UI, a thousand warns can be reached within few minutes.

But we can sort it out. I will release a PR shortly where the behavior on both Nuxt and Vue is just like that:

https://github.com/radix-vue/radix-vue/assets/60471784/28256a3d-35c8-45d0-808b-8f212a328304

**Comment by zernonia** [comment]
@BayBreezy  This issue has been fixed in `0.1.18`. You should be able to use this component without this warning anymore 😁

However you might still see some warning from other components, we are working on them!

**Comment by BayBreezy** [comment]
Thank you @zernonia ! I already gave it a spon lol. I am seeing some weird behavior with the accordion. I will create a repro and share the link soon

**Comment by mikerockett** [comment]
I’m seeing this same issue with the Menubar* components. Are there plans to fix those too?

**Comment by zernonia** [comment]
Yup. Worry not! 
https://github.com/radix-vue/radix-vue/pull/302

**Comment by peterbud** [comment]
I experience the same issue with DialogTrigger component
