### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by edtorba** [radix-vue/radix-vue#263]
In short, there is a missing toast component, which can be found at https://www.radix-ui.com/docs/primitives/components/toast. I'm ready to address this issue. Once approved, kindly assign the task to me, and I'll immediately begin the work.

**Comment by khairulhaaziq** [comment]
you are welcomed to do it! Thanks

**Comment by edtorba** [comment]
Want me to spin up similar issues/phases like you guys did for other components?

**Comment by khairulhaaziq** [comment]
> Want me to spin up similar issues/phases like you guys did for other components?

no need

**Comment by khairulhaaziq** [comment]
hi Im gonna close this, @edtorba I dont think it is worth anyone's time to do a toast component, I just found out about [notivue](https://github.com/smastrom/notivue) which is an awesome library, there are some more really great vue toast library such as vue-sonner as well that is really well developed and takes month if not years of hard work into it. I think lets just use them rather than spending our time on it, lets focus on our current components first and make them.as reliable and as easy to use/adopt
