### ISSUE TITLE
[Feature]: Generics for Combobox

### ISSUE THREAD

**Issue by pietdevries94** [radix-vue/radix-vue#438]
### Describe the feature

I'm not entirely sure how we would implement them, but I notice the DX of the combobox is not amazing regarding the filter function and the emits for model-value, because it's not fully type save. I feel that it would be rather complex to implement this nicely because of the composable nature of radix. I might have a go sometime to experiment with solutions, but I'm also interested to hear ideas of the community/creators about this and if this is actually something we should want to persue.

### Additional information

- [x] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Thanks for bringing this up @pietdevries94 .

Actually the use of `filter-function` is an alternative way. You can also render the list [as such](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Combobox/story/ComboboxObject.story.vue#L70-L124).  (Will add more examples in docs soon)

As for the `modelValue`, you are right that due to the composable nature of Radix, we cant technically inferred the `modelValue` properly without adding more props, even with Vue3.3 generic component.  However you are welcome to experiement!!!
