### ISSUE TITLE
[Bug]: dropdown doesn't is not scrollable when there's not enough room to display it in full

### ISSUE THREAD

**Issue by remiconnesson** [radix-vue/radix-vue#452]
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://www.radix-vue.com/components/dropdown-menu.html#dropdownmenu

### Steps to reproduce

Open https://www.radix-vue.com/components/dropdown-menu.html#dropdownmenu and shorten your window so the dropdown doesn't fit.

then, open https://www.radix-ui.com/primitives/docs/components/dropdown-menu  and shorten your window so the dropdown doesn't fit.

### Describe the bug

# In the current `radix-vue`

In the gif below, we can notice the dropdown is too big for the space remaining, so a part of it is unreachable. As the dropdown remove the scrollability of the page.

![radix-vue-current-dropdown](https://github.com/radix-vue/radix-vue/assets/28846642/79572add-c6c4-4230-8180-8658da2a2226)

# in the original radix

In the original radix, when there's not enough space, the dropdown is trimmed to fit in the available space and use a scroll area inside to display the content
![radix-original-dropdown](https://github.com/radix-vue/radix-vue/assets/28846642/b99711cc-0659-48a2-853f-c0781cadae3c)

### Expected behavior

The expected behavior would be to match the orginal radix-ui's.

**Comment by romansp** [comment]
@remiconnesson it's expected behavior for Radix Vue/Radix UI primitives.

In your gif you're comparing Radix-vue primitive and Radix UI Theme component. If you look at [Radix UI primitive](https://www.radix-ui.com/primitives/docs/components/dropdown-menu) and repeat your test it doesn't become scrollable by default.

Primitives are low-level UI components and should be treated as base layer of your app components. Primitives like `DropdownMenu` only compute available height/width and expose these as CSS variables and will not constrain content by default.

So components in original Radix UI Theme use CSS variables to set `max-height` properties for their scrollable content as shown here: https://github.com/radix-ui/themes/blob/bfab82fac4707e5ab633aebd702f5c985c45c019/packages/radix-ui-themes/src/components/dropdown-menu.css#L3-L6

I also left comment in another issue here explaining how these CSS variables could be used together with tailwindcss https://github.com/radix-vue/radix-vue/issues/451#issuecomment-1762309291 to constrain content size manually.

**Comment by remiconnesson** [comment]
Thank you very much for clarifying, I did not know all this
