### ISSUE TITLE
[Feature]: Add data-[primitive-name] to every primitive

### ISSUE THREAD

**Issue by zernonia** [radix-vue/radix-vue#505]
### Describe the feature

eg: `ComboboxRoot` will render `<div data-radix-combobox-root>...</div>`

Usage:
- Targeted styling using css's data attributes
- Easier navigation looking through DOM

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
I second this cause it's really hard to find related components in devtools

in dev mode, it's also good to add [`vite-plugin-vue-inspector`](https://github.com/webfansplz/vite-plugin-vue-inspector) to the vitepress doc

**Comment by zernonia** [comment]
@sadeghbarati what do you mean good to add the inspector to vitepress doc yaa? Why is that needed? 🤔

**Comment by sadeghbarati** [comment]
It's an optional vite plugin for dev mode, not required, it doesn't affect the production build

It just helps navigate to the code within VSCode,

I'll share a record

**Comment by sadeghbarati** [comment]
After testing with vite-plugin-vue-inspector I take back what is said 🤣 

I thought it would show component names when I hover each component

https://stackblitz.com/edit/fu91hk?file=vite.config.js

**Comment by sadeghbarati** [comment]
I would vote for `radix-vue-combobox-root` but I'm also ok with `data-radix-vue-combobox-root`

`radix-vue-combobox-root` and `data-radix-vue-combobox-root` ✅ 

only radix `data-radix-combobox-root` ❌ 

---

Can you assign it to me?

**Comment by ferferga** [comment]
I believe that, instead of forcing an specific attribute name (which also bloats the final bundle), a better solution (and opt-in by default, not forced to anyone) is to use provide/inject (in a similar way to how Vuetify defaults work), so at Primitive we do something like:

v-bind="mergeProps($attrs, injectedAttrs)"

I'm interested in getting this done if you like the idea @zernonia

**Comment by zernonia** [comment]
I think adding 1 attr per file wouldn't really "bloats" the final bundle tho.
Opt-in to this feature is a good idea. But I failed to see how this could work in our case? Can you shine some light on how Vuetify did it? Perhaps a link to their code please? 😁

**Comment by ferferga** [comment]
[This is what I mean](https://vuejs.org/guide/components/provide-inject#provide-inject) (in case it wasn't clear enough in my first message)

The idea is that we can inject into ``Primitive.ts`` a ``radix-attrs`` key, which is binded to the element. [A sample SFC](https://play.vuejs.org/#eNq1U02P0zAQ/SuzFlJaKWlFy6l0kWC1EssBKkDikkuaTLvuJrblj2ylqv+dsZ2kBJaKCzfPzJvxm493Yu+VmrUO2YqtTam5smDQOvUuF7xRUls4gdKy5RXCGXZaNpAQPBnCd7JRr7vAbB4sXy95O0IsRojFC4jlCLHsEbnYOVFaLgWUNS+fPhaiqlFPpnDKBUAphZE1zmq5nyR3HoDVTTKlxLPP7ZhPEl1U/JgV1mqTpDE1kSIkJKtRZcqc5mI9j8OgMZBhsVF1YZEsgHXoMTw7Y9EZnbmEeR+N3ca0OBt6r+e/1GMps4a62PH97GCkoD0EdjkrCc6J0Bfluzc5W0XePlbUtXz+FHxWO0x7f/mI5dML/oM5el/ONhoN6hZzNsRsofdoY/j+22c80nsINrJyNaGvBL8ibcB5jhH2wcU5XnCB7UNYNRf77+b+aFGYvilP1CPPAZ8zWryf1N9av9Bdzt6EPNoYTXG4vD8u+douK972uzK1tN3m1vPo/31Tw+3+5z/C9V9TJBcHLG0KDdIwNloqMxJn0I2Xhu2QWMFt9xxrwSvlH7nfZBn8QHAGoYCts5YkuZMaKmz8T7oIIlVOK2nQpB4C9pEbeJaurmCLZCFsNG+45S2SdKkbgcJmWf9FV7XNtlxUt3RgQ3uTV4FvOvQzzdmguoekuVSDZUeul2C0rsz8/BPqm64l)

This way, we can inject any custom event handler, attribute or even classes (which is what I'm looking forward to) to all radix elements, being much more flexible that what you propose (and I don't see any drawback).

If an user wants to target specifically a Combobox, it's only needed to provide the same key with the new attributes in it. Given your example of the Combobox, using the Combobox component definition from the documentation (and stripping unneeded parts), this is how would work:

```
<script setup lang="ts">
import { provide } from 'vue'

provide('radix-attrs', {
   'data-radix-combobox': ''
})
</script>

<template>
   <ComboboxRoot>
       ....
   </ComboboxRoot>
</template>
```

That would add a data-radix-combobox attribute to all child components, and even allow us to pass custom values (instead of an empty string.

There's a demonstration of how a child can override a parent's provide in [this SFC](https://play.vuejs.org/#eNqdUk1PwzAM/StWLgVpbGJwgoEEiAMcAAHHXqrWjIw0iRK3TJr633HSD9g0NsTN9ntOnu23ElfWjusKxZmY+dxJS+CRKnuZalla4whWYJ2pZYHQwJszJSRMTwb4xpT2uAPGk5iF95LzNcZ0jTHtGanu3j5IXFbI5VFG5HwyguQOshLoHYGMBYU1Ksi502jUlBxy62zSymWhnBCWVmWEnAHMoooYdskUJi3SCuR4NvnRIkaCfG70m5yPF95oXsYq0FMR/pQK3aMlabRPxRlEJGCZUubzPtbIVTjq6/k75h9b6gu/DLVUPDn06GpMxYBR5uZILXz78oBLjgewNEWlmL0DfEZvVBU0trTrShcs+wcvqr2LF5F6/upvl4Ta90MFoYHZRH4q+D5hU7+N/i33ZHwa+1Ld8BaH8++yk9QLzGm01VbRE3wJTx0NC7jownWPHO7xjqnRfToZho0+splj6/SfhvZdDipk3fln1QtmJQ2PGT3llaHBUi1301CDz/evYnMDf53/vwNsl9x8AZm3Xpc=).

How Vuetify works is quite similar, but it uses their own custom plugin (which Radix doesn't have, since they're standalone components, one of my favourite things about it honestly) for injection and they do some stuff in a non-so-much Vue way (like merging, they use their custom function, when Vue provides mergeProps). [Here's where their main logic happens](https://github.com/vuetifyjs/vuetify/blob/master/packages/vuetify/src/composables/defaults.ts) though.

**Comment by zernonia** [comment]
Will be closing this. Having `data-[primitive-name]` might not be the best because we have some primitive built on top of another, afraid that this might cause even more confusion. 

And the initial idea is to allow easier navigation through the DOM. With [Devtool Inspector](https://devtools-next.vuejs.org/getting-started/features#inspector), I would recommend to use this approach to inspect and navigate to component instead.
