### ISSUE TITLE
[Feature]: Select, Calendar, DropDown by default set dir to ltr even when html dir is rtl

### ISSUE THREAD

**Issue by lord007tn** [radix-vue/radix-vue#719]
### Reproduction

https://codesandbox.io/p/devbox/shadcn-vue-selectdemo-forked-gxptxq

### Describe the bug

I set global dir for html to be `dir='rtl'`
Select, calendar, dropdown seems to have a default `dir='ltr'` so everytime i should force them to be `dir='auto'` so they can have parent HTML dir
it seems like auto is not a valid value in radix components 
so we need to support it in shadcn components as default value

### System Info

```bash
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7950X 16-Core Processor
    Memory: 6.19 GB / 31.16 GB
  Binaries:
    Node: 18.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.3 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (121.0.2277.128)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @vueuse/core: ^10.7.2 => 10.7.2
    radix-vue: ^1.4.7 => 1.4.7
    vue: ^3.4.19 => 3.4.19
```

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by Saeid-Za** [comment]
Very well then! 
Here is my proposal for implementation design of a `ConfigProvider` replacement/enhancement. There are several ways to implement such feature:

The Challenge here is how to `provide` first direction state for SSR compatibility, the rest of the implementation is described before in https://github.com/radix-vue/radix-vue/issues/719#issuecomment-1974683517 and  https://github.com/radix-vue/radix-vue/issues/719#issuecomment-1974683521.
## Using Wrapper Component (Current Implementation)

```vue
<script setup lang="ts">
import { ConfigProvider } from 'radix-vue'
</script>

<template>
  <ConfigProvider initialDir="ltr">
    <slot />
  </ConfigProvider>
</template>
```

We would only need to rename `dir` field in `ConfigProviderContextValue` to `initialDir` because we are changing the meaning of the variable in this implementation.

## Using Vue Plugin
By using a plugin we could provide a global configuration, from [vue docs](https://vuejs.org/guide/reusability/plugins), one of the use cases for vue plugins are:
>Make a resource [injectable](https://vuejs.org/guide/components/provide-inject) throughout the app by calling [app.provide()](https://vuejs.org/api/application#app-provide).

user would create such plugin and this value would be used as `initial value` on reactive direction implemented on radix codebase.

```ts
import { createRadixConfig } from "radix-vue"
import { createApp } from 'vue'
import App from './App.vue'
import './style.css'

const radixConfig = createRadixConfig({
  initialDir: 'ltr',
})

createApp(App)
.use(radixConfig)
.mount('#app')
```

I'd personally recommend going this direction as it has no overhead of a [render-less component](https://vuejs.org/guide/components/slots.html#renderless-components) and aligns better with vue itself, IMO using Provider components are better left in react, as far a I know bigger parts of vue ecosystem does not follow Provider component pattern.
Although it does have a bit lower DX compared to previous approach, it could be encapsulated to a module for `nuxt` but for the previous approach there is no such luxury. there is a bit trade-off here.

Let me know your thoughts and if this sound OK to you, i'd be happy to helping execute this idea.

**Comment by zernonia** [comment]
Thanks for awesome suggestion @Saeid-Za !

The reason with `ConfigProvider` components is so that the config doesn't ties to only one setup (namely `main.ts`). 
Every page or component can have independant config, which is what Vue plugin does not offer.

Even though we can export a custom provide function to provide and inject similar config, but the idea of "wrapping" with components is more appealing to me.

What do you think?

**Comment by Saeid-Za** [comment]
@zernonia 
Thanks for the explanation !
I haven't thought of such a use case, I thought that this is a global level config level provider, you are absolutely right.

Considering the the fact that `initialDir` is indeed global level due to it's scope being related to SSR, I prefer it being a plugin level provide.

Nevertheless, ConfigProvider could not be replaced which i thought it could, here's an idea, why not support both approaches?

With this new approach, the flexibility of current implementation is preserved and any plan for adding nuxt module level configuration would be open.

**Comment by zernonia** [comment]
We can do that @Saeid-Za .

However, I also thought about another possible solution, we can utilize `useTextDirection` and `ConfigProvider` together. 
https://stackblitz.com/edit/7kcx91?file=src%2FApp.vue

This way it offers much more flexibility to the user, also support Vite/Nuxt.

**Comment by Saeid-Za** [comment]
Since users should always provide something to the provider for direction to work, it seems that there is no way around it.
I like the simplicity of your approach and overall i think it is the best approach.

There is no code changes required right?
Only new documentation regarding Directionality of the App

**Comment by zernonia** [comment]
Yup. I think so. We can add a guide to the doc mention about "internationalization (RTL)" 👍🏻

**Comment by Saeid-Za** [comment]
Sure !
I'll add documentation for i18n integrations and multi direction support.
