### ISSUE TITLE
[Feature]: Year and month picker for date picker

### ISSUE THREAD

**Issue by DamianGlowala** [radix-vue/radix-vue#741]
### Describe the feature

Currently, picking a date far off from the currently displayed month (e.g. two years earlier), means clicking countless times on the prev/next button. It would be great to enhance the date picker with a year and month picker views.

Great example is Prime Vue: https://primevue.org/calendar/#basic

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by sadeghbarati** [comment]
@DamianGlowala please look at this PR for more context 

month and year is opt-in feature so you could display it wherever you want 

https://github.com/radix-vue/radix-vue/pull/674#issuecomment-1972135499

**Comment by DamianGlowala** [comment]
Thanks for letting me know! I'll have a look and close the issue once I confirm it is all working fine :)

**Comment by sadeghbarati** [comment]
@epr3 

Hi I have a question about adding other Calendar Systems like `PersianCalendar` within `radix-vue` Calendar

`react-aria` has 

```
<Provider locale={(locale || defaultLocale) + (calendar && calendar !== preferredCalendars[0].key ? '-u-ca-' + calendar : '')}>
```

For managing Calendar Systems, how we can do it in `radix-vue` Calendar can you add story or example in documentation?

**Comment by zernonia** [comment]
Any update on this @DamianGlowala  😁 If it's all good we can close this

**Comment by DamianGlowala** [comment]
@zernonia I think we can close this! Haven't tried implementing year and month pickers yet, but the above coments suggest this is achievable :)

**Comment by mkeyy0** [comment]
I want to say that implementing year-month select when the `numberOfMonths` is set as `1` was quite straightforward. Still, when it's more than `1` it's not as easy, because when you set placeholder programmatically it basically can be set on any view, and values on the calendar won't be updated I guess it needs to be done with the grid somehow, but I'm not sure. Maybe someone has some working examples of that?
@zernonia I would be thankful!
