### ISSUE TITLE
[Feature]: Add provider functions as alternatives to provider components

### ISSUE THREAD

**Issue by remonke** [radix-vue/radix-vue#823]
### Describe the feature

I suggest using functions to provide contexts instead of components. While provider components are common in React, I believe Vue's distinctive features should be embraced rather than emulating React. This approach reduces nesting and enables usage beyond templates. Provider components will remain, serving as wrappers for these provider functions. The syntax could be as follows:

```vue
<script setup lang="ts">
const nuxtUseId = () => useId()

radixProvideConfig({
  useId: nuxtUseId,
})
radixProvideTooltip({
  ignoreNonKeyboardFocus: true
})
radixProvideToast()
</script>

<template>
  <WhateverChild />
</template>
```

Instead of:

```vue
<script setup lang="ts">
const nuxtUseId = () => useId();
</script>

<template>
  <RadixConfigProvider :use-id="nuxtUseId">
    <RadixTooltipProvider ignore-non-keyboard-focus>
      <RadixToastProvider>
        <WhateverChild />
      </RadixToastProvider>
    </RadixTooltipProvider>
  </RadixConfigProvider>
</template>
```

### Additional information

- [X] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
The provider components were designed so that it brings clarity to dev, and make sure all the child component received the appropriate provided context, and not merely emulating React.

Also, some provider has functionalities other than just "provide" the context. Do check out 

https://github.com/radix-vue/radix-vue/blob/3d8dcb43fce20a5574416651e6c1c38c315e7f75/packages/radix-vue/src/Tooltip/TooltipProvider.vue#L1-L98

and 

https://github.com/radix-vue/radix-vue/blob/3d8dcb43fce20a5574416651e6c1c38c315e7f75/packages/radix-vue/src/Toast/ToastProvider.vue#L1-L93

**Comment by zernonia** [comment]
Could you share on what do you mean by function? 

The `Provider` component is needed for components. If you are referring to `ConfigProvider`, that's different case.

**Comment by zernonia** [comment]
As we cant replace provider components with provider functions (as mentioned here), I'm going to close this out.
