### ISSUE TITLE
[Feature]: Autocomplete Control

### ISSUE THREAD

**Issue by maslamhmt** [radix-vue/radix-vue#927]
### Describe the feature

Hi! I'm delighted to try radix-vue controls. Could you please add an auto-complete control for database filtering and selection?

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment]
Hi @maslamhmt . Please add more context on what this feature means. Either show show example, or explain in much more details 😁

**Comment by unpseudocomplique** [comment]
> Hi @maslamhmt . Please add more context on what this feature means. Either show show example, or explain in much more details 😁

I will add more contexte because i think this is the same request as i have.

Combobox is great but it's limited to client side filter. In a real world app 90% have to be filter by backend. 

In fact the component need a component that when reaching bottom of scroll fetch next page (so maybe require a new emit "fetch-next-page") a backend filter function like when you type it trigger an async function that will replace the original array and reset "currentPage" to 0

I hop this was clear !

**Comment by maslamhmt** [comment]
Hi @zernonia and @unpseudocomplique, Autocomplete Control is the same as Combobox. The difference is Autocomplete control uses items from the database, like binding data from the database table. By default, it will not show you the items. When you type something, it will search from the database with respective data and bind it with autocomplete control to show you. For Example, I want to search for some country. When I try to search Pakistan or India, I have to write just `pak` it will show Pakistan as a result in the dropdown. I hope this one clears.

**Comment by zernonia** [comment]
Thanks for the context @maslamhmt ! This is something already supported. You can checkout the `async` story here

https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Combobox/story/ComboboxAsync.story.vue

**Comment by zernonia** [comment]
Closing this as stale and we already have this feature implemented 😁

**Comment by xak2000** [comment]
@zernonia I'm sorry to bring up an old issue, but I think there was some miscommunication in the comments.

Yes, we can use async loading with `Combobox` like in [the example above](https://github.com/radix-vue/radix-vue/blob/main/packages/radix-vue/src/Combobox/story/ComboboxAsync.story.vue).


But an "Autocomplete" control should provide more than that. The biggest difference between client-side `Combobox` and server-side `Autocomplete` is the support of pagination.

When the full list is known beforehand on the client, we usually just throw the whole list into the component, right? Maybe we filter it by a query locally, but that's all. But when a server returns the data for the list, then in 99% cases this data is paginated, so the list will always display just part of the data matching the filter.

This creates a new requirement for the UI: to display pagination inside of the dropdown. It could be `[<] [1] .. [3] [>]` pagination or "scroll to load next page" pagination, but the pagination is very important anyway.

To be fair, a support for pagination would be beneficial even for client-side `Combobox` because when there are 1000+ items in the list, it becomes very unresponsive (almost unusable as each action makes Browser hang for several seconds). But for server-side lists it is not just "nice to have", but a requirement.

Probably every developer could implement such component by themselves on top of `Combobox`, but I think it is not a trivial task to do it properly. Many gotchas.

Also I didn't try it yet, but I feel that some API/events could be required to be exposed to do it properly. Such as an event thrown by `Combobox` when user scrolled the list to 80% to the bottom (so, next page should be starting to load), etc.

So, maybe it would be good to have support of such functionalities out of the box.

P.S. An example of such Combobox to visualize what I mean:

![Image](https://github.com/user-attachments/assets/bcf18aa4-8618-45a2-afe2-0b3595d97581)
